id: I85DC3838
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:36:06.798022+00:00
last_modified: 2022-12-14 10:36:06.798026+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-09-22T23:19:33.676Z'
  creationid: S.J.
  eft-text-id: UT22084-087-003
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_498-Tantra_of_the_Blue-Clad_Vajrapani-v1
bases:
  FF44:
    source_metadata: null
    order: 1
    base_file: FF44.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
